package frc.robot.state.sequencer;

public enum Sequence {
  RESET,

  INTAKE_ALGAE_L2,
  INTAKE_ALGAE_L3,
  INTAKE_ALGAE_FLOOR,
  SCORE_ALGAE_BARGE, // Barge score
  SCORE_ALGAE_PROCESSOR,

  INTAKE_CORAL,
  SCORE_CORAL_L1,
  SCORE_CORAL_L2,
  SCORE_CORAL_L3,
  SCORE_CORAL_L4
}
